### ISSUE TITLE
Export network coefficients to text that human understandable

### ISSUE THREAD

**Issue by james34602** [attractivechaos/kann#17]
If a function that can print MLP to weights and bias in text file would be great.
As the function could help building a NN without extra overhead.

**Comment by attractivechaos** [comment]
> building a NN without extra overhead

What overhead? It is a bad idea to print floating point numbers in plain text. KANN provides functions to save/load models and parameters. Please use those.

**Comment by james34602** [comment]
What my thoughts is user have chance to explore their model easier, or I would say print the coefficients with just one function call. Something like get_weights() in Keras.

**Comment by Levalicious** [comment]
I would be in favor of the addition of this feature, if possible. It would be nice to be able to make networks 'exportable' in some format other than the kann format, so that small networks can be put directly into code, or for other programs that support GPU training.
