### ISSUE TITLE
Why isn't KANN scalable?

### ISSUE THREAD

**Issue by tianfanzhu** [attractivechaos/kann#24]
Hi,
I was wondering about the statement in the README - "KANN is not as scalable, but it is close in flexibility, has a much smaller code base and only depends on the standard C library.". 

Why isn't KANN scalable and why isn't it it suitable for training deeper networks?

**Comment by shipleyxie** [comment]
train a deeper NN need much ops, which require a lot of time. 
so , if you choose Kann , emm...some kind of inefficiency

**Comment by attractivechaos** [comment]
It doesn't use GPU. For large matrix multiplication and 2d CNN, GPU is much faster than any possible CPU implementations.
