### ISSUE TITLE
Why accuracy does not increase anymore at specific epoch?

### ISSUE THREAD

**Issue by co7ding** [attractivechaos/kann#42]
Given MNIST CNN example, validation cost does not increase from approximately epoch 11. So, running more epochs is useless since validation cost will be only increasing or decreasing in near minimum cost value which is the validation cost of epoch 11. Could you explain why this happens and how to solve it? (I also tested using a variety of structures of CNN, but there was no big difference.)

**Comment by attractivechaos** [comment]
You have reached the capability of the model. You can't do much unless you change the model.

**Comment by co7ding** [comment]
I tried many models by changing the structure, but all structures that I tried could not reach an accuracy of over 90%. Did you get a high accuracy than 90% in CNN example?

**Comment by attractivechaos** [comment]
Just run the command lines in "examples". You can trivially get 97% validation and test accuracy even with MLP.

**Comment by co7ding** [comment]
Oh, I misunderstood the ```mnist-eval.pl``` code. Sorry for a stupid question. Thank you :)
