### ISSUE TITLE
Exporting weights?

### ISSUE THREAD

**Issue by GooseXP** [attractivechaos/kann#46]
I am hoping to train a KANN model with a genetic algorithm, but in order to do this I will need to be able to get an array of  network weights, and I did not see a way of doing this in the documentation. I could be missing something obvious though.

**Comment by attractivechaos** [comment]
There is not an API for this. You can directly access `kad_node_t::x`. You can get the list of nodes from `kann_t::v`.

**Comment by GooseXP** [comment]
That will do fine thank you
